/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Amelia Wolf
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        admin = new javax.swing.JMenu();
        distribuidores = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenuItem();
        vendedores = new javax.swing.JMenuItem();
        comisiones = new javax.swing.JMenuItem();
        inventario = new javax.swing.JMenu();
        productos = new javax.swing.JMenuItem();
        materiaprima = new javax.swing.JMenuItem();
        procesos = new javax.swing.JMenu();
        produccion = new javax.swing.JMenuItem();
        ingresomatpri = new javax.swing.JMenuItem();
        venta = new javax.swing.JMenuItem();
        interno = new javax.swing.JMenu();
        listadoven = new javax.swing.JMenuItem();
        listadomatpri = new javax.swing.JMenuItem();
        listadopro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        admin.setText("Administración");

        distribuidores.setText("Distribuidores");
        distribuidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                distribuidoresMouseClicked(evt);
            }
        });
        distribuidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distribuidoresActionPerformed(evt);
            }
        });
        admin.add(distribuidores);

        clientes.setText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        admin.add(clientes);

        vendedores.setText("Vendedores");
        vendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedoresActionPerformed(evt);
            }
        });
        admin.add(vendedores);

        comisiones.setText("Comisiones");
        admin.add(comisiones);

        jMenuBar1.add(admin);

        inventario.setText("Inventario");

        productos.setText("Productos");
        inventario.add(productos);

        materiaprima.setText("Materia Prima");
        inventario.add(materiaprima);

        jMenuBar1.add(inventario);

        procesos.setText("Procesos");

        produccion.setText("Producción");
        procesos.add(produccion);

        ingresomatpri.setText("Ingreso Materia Prima");
        procesos.add(ingresomatpri);

        venta.setText("Venta");
        procesos.add(venta);

        jMenuBar1.add(procesos);

        interno.setText("Interno");

        listadoven.setText("Listado Ventas realizadas");
        interno.add(listadoven);

        listadomatpri.setText("Listado Materias Primas");
        listadomatpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadomatpriActionPerformed(evt);
            }
        });
        interno.add(listadomatpri);

        listadopro.setText("Listado Productos");
        interno.add(listadopro);

        jMenuBar1.add(interno);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void distribuidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribuidoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distribuidoresActionPerformed

    private void vendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendedoresActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesActionPerformed

    private void listadomatpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadomatpriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadomatpriActionPerformed

    private void distribuidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distribuidoresMouseClicked
        VentanaDistri distri = new VentanaDistri();
        
        int x = (escritorio.getWidth() / 2) - distri.getWidth() /2;
        int y = (escritorio.getHeight() / 2) - distri.getHeight() /2;

        if (distri.isShowing()){
            distri.setLocation(x,y);
        }
        else{
            escritorio.add(distri);
            distri.setLocation(x,y);
            distri.setVisible(true);
        }
        
    }//GEN-LAST:event_distribuidoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu admin;
    private javax.swing.JMenuItem clientes;
    private javax.swing.JMenuItem comisiones;
    private javax.swing.JMenuItem distribuidores;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem ingresomatpri;
    private javax.swing.JMenu interno;
    private javax.swing.JMenu inventario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listadomatpri;
    private javax.swing.JMenuItem listadopro;
    private javax.swing.JMenuItem listadoven;
    private javax.swing.JMenuItem materiaprima;
    private javax.swing.JMenu procesos;
    private javax.swing.JMenuItem produccion;
    private javax.swing.JMenuItem productos;
    private javax.swing.JMenuItem vendedores;
    private javax.swing.JMenuItem venta;
    // End of variables declaration//GEN-END:variables
}
