/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Distribuidor;
import modelo.IngresoDetalle;
import modelo.MateriaPrima;

/**
 *
 * @author Amelia Wolf
 */
public class VentanaIngMatPri extends javax.swing.JInternalFrame {

    private DefaultTableModel mTabla;
    private DefaultComboBoxModel mDis;
    private DefaultComboBoxModel mMatPri;
    
    /**
     * Creates new form VentanaIngMatPri
     */
    public VentanaIngMatPri() {
        initComponents();
        mTabla = (DefaultTableModel) tblmatpri.getModel();
        mDis = (DefaultComboBoxModel) cmbdistri.getModel();
        mMatPri = (DefaultComboBoxModel) cmbmatpri.getModel();
        cmbmatpri.setActionCommand("cmbmatpri");
        btnterminar.setActionCommand("terminar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Haciendo Listeners de los txt y btn
    public int getDistribuidor() {
        return cmbdistri.getSelectedIndex();
    }

    public double getTotal() {
        return Double.parseDouble(txttotal.getText().trim());
    }

    public int getMatPri() {
        return cmbmatpri.getSelectedIndex();
    }

    public String getNombre() {
        return txtnombre.getText().trim();
    }

    public int getPrecio() {
        return Integer.parseInt(txtprecio.getText().trim());
    }

    public int getCodigo() {
        return Integer.getInteger(txtcodigo.getText().trim());
    }

    public int getCantidad() {
        return Integer.getInteger(txtcantidad.getText().trim());
    }

    public void addListenerAgregar(ActionListener listen) {
        btnagregar.addActionListener(listen);
    }

    public void addListenerSelectMatPri(ActionListener listen) {
        cmbmatpri.addActionListener(listen);
    }

    public void addListenerTerminar(ActionListener listen) {
        btnterminar.addActionListener(listen);
    }
    
    public void addListenerEliminar(ActionListener listen) {
        btneliminar.addActionListener(listen);
    }
    
    public boolean revisartabla(){
        if (tblmatpri.getRowCount() == 0) {
                return false;
            }
        return true;
    }

    //Vaciar la tabla 
    public void limpiarTabla() {
        for (int i = mTabla.getRowCount() - 1; i >= 0; i--) {
            mTabla.removeRow(i);

        }
        txttotal.setText("0");
    }
    
    //"Crear" tabla de Ingreso detalle
    public void cargarIngDet() {
        int cantidad = Integer.parseInt(txtcantidad.getText());
        double precio = Double.parseDouble(txtprecio.getText());
        double total = cantidad * precio;
        String nombre = txtnombre.getText();
        int codigo = Integer.parseInt(txtcodigo.getText());
        double totaldefenitivo = total + Double.valueOf(txttotal.getText());

        txttotal.setText(String.valueOf(totaldefenitivo));

        mTabla.addRow(new Object[]{
            codigo,
            nombre,
            precio,
            cantidad,
            total});
    }
    
    //Cargar los datos de les ComboBox
    public void cargarDistribuidor(ArrayList<Distribuidor> listaDis) {
        mDis.removeAllElements();
        for (int i = 0; i < listaDis.size(); i++) {
            mDis.addElement(listaDis.get(i).getNombreDis());
        }
    }

    public void cargarMatPri(ArrayList<MateriaPrima> listaMatPrimas) {
        mMatPri.removeAllElements();
        for (int i = 0; i < listaMatPrimas.size(); i++) {
            mMatPri.addElement(listaMatPrimas.get(i).getNombreMatPri());
        }
    }
    
    public void cargarDatosMatPri(MateriaPrima matpri) {
        txtnombre.setText(matpri.getNombreMatPri());
        txtcodigo.setText(String.valueOf(matpri.getCodigoMatPri()));
    }
    
    public boolean revisaDatos() {
        if (txtcantidad.getText().replaceAll(" ", "").isEmpty()|| txtprecio.getText().replaceAll(" ", "").isEmpty()
                || txtnombre.getText().replaceAll(" ", "").isEmpty()||txtcodigo.getText().replaceAll(" ", "").isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Datos incompletos, por favor ingrese una cantidad");
            return false;
        }
        return true;
    }
    
    public ArrayList<IngresoDetalle> ingresodetalle() {
        ArrayList<IngresoDetalle> ingdet = new ArrayList();
        for (int i = 0; i < tblmatpri.getRowCount(); i++) {
            IngresoDetalle detallito = new IngresoDetalle();
            detallito.setMatPrima(Integer.parseInt(tblmatpri.getValueAt(i, 0).toString()));
            detallito.setCostoUni(Double.parseDouble(tblmatpri.getValueAt(i, 2).toString()));
            detallito.setCantidad(Integer.parseInt(tblmatpri.getValueAt(i, 3).toString()));
            detallito.setTotal(Double.parseDouble(tblmatpri.getValueAt(i, 4).toString()));
            
            ingdet.add(detallito);
        }
        return ingdet;
    }
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldistri = new javax.swing.JLabel();
        cmbdistri = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblmatpri = new javax.swing.JLabel();
        lblcuantos = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        cmbmatpri = new javax.swing.JComboBox<>();
        btneliminar = new javax.swing.JButton();
        btnterminar = new javax.swing.JButton();
        lblprecio = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmatpri = new javax.swing.JTable();

        setClosable(true);
        setTitle("Ingreso Materia Prima");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Ingreso"));

        lbldistri.setText("Distribuidor: ");

        jLabel2.setText("Total: ");

        txttotal.setEditable(false);
        txttotal.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldistri)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbdistri, 0, 129, Short.MAX_VALUE)
                    .addComponent(txttotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldistri)
                    .addComponent(cmbdistri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Materias Primas"));

        lblmatpri.setText("Materia Prima:");

        lblcuantos.setText("Cuantos:");

        btnagregar.setText("Agregar");

        btneliminar.setText("Eliminar");
        btneliminar.setEnabled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnterminar.setText("Terminar Ingreso");

        lblprecio.setText("Precio:");

        lblnombre.setText("Nombre:");

        lblcodigo.setText("Codigo:");

        txtnombre.setEditable(false);

        txtcodigo.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblprecio)
                            .addComponent(lblcuantos))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcantidad)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblmatpri)
                        .addGap(17, 17, 17)
                        .addComponent(cmbmatpri, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblnombre)
                    .addComponent(lblcodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombre)
                    .addComponent(txtcodigo))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnterminar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmatpri)
                    .addComponent(cmbmatpri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprecio)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcodigo)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcuantos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnterminar)
                    .addComponent(btnagregar)
                    .addComponent(btneliminar))
                .addContainerGap())
        );

        tblmatpri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Materia Prima", "Precio", "Cantidad", "Total"
            }
        ));
        tblmatpri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmatpriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmatpri);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Datos ingreso");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblmatpriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmatpriMouseClicked
        int sel = tblmatpri.getSelectedRow();
        if (sel == -1) {
            if (tblmatpri.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No hay registros");
            }
        } else {
            txtcodigo.setText(tblmatpri.getValueAt(sel, 0).toString());
            txtnombre.setText(tblmatpri.getValueAt(sel, 1).toString());
            txtprecio.setText(tblmatpri.getValueAt(sel, 2).toString());
            txtcantidad.setText(tblmatpri.getValueAt(sel, 3).toString());
            btneliminar.setEnabled(true);
            btnagregar.setText("Cancelar");
            btnagregar.setActionCommand("cancelar");
        }
    }//GEN-LAST:event_tblmatpriMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int sel = tblmatpri.getSelectedRow();
        double can = Double.valueOf(tblmatpri.getValueAt(sel, 4).toString());
        double totaldefenitivo = Double.parseDouble(txttotal.getText()) - can;

        txttotal.setText(String.valueOf(totaldefenitivo));
        mTabla.removeRow(sel);
        cancelarAction();
    }//GEN-LAST:event_btneliminarActionPerformed

    public void cancelarAction() {
        btneliminar.setEnabled(false);
        btnagregar.setText("Agregar");
        btnagregar.setActionCommand("agregar");
        tblmatpri.clearSelection();
        limpiarDatos();
    }

    public void limpiarDatos() {
        txtcodigo.setText("");
        txtnombre.setText("");
        txtcantidad.setText("");
        txtprecio.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnterminar;
    private javax.swing.JComboBox<String> cmbdistri;
    private javax.swing.JComboBox<String> cmbmatpri;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcuantos;
    private javax.swing.JLabel lbldistri;
    private javax.swing.JLabel lblmatpri;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JTable tblmatpri;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
