/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.MateriaPrima;
import modelo.Produccion;
import modelo.Producidos;
import modelo.Producto;


/**
 *
 * @author Amelia Wolf
 */
public class VentanaProduRea extends javax.swing.JInternalFrame {
    
    private DefaultTableModel mTabla;
    
    /**
     * Creates new form VentanaProduRea
     */
    public VentanaProduRea() {
        initComponents();
        mTabla = (DefaultTableModel) tblprodurea.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public int getcodigoVenta(){
        int sel = tblprodurea.getSelectedRow();
        int venta = (Integer) tblprodurea.getValueAt(sel, 0);   
        return venta;
    }
    
    //"Crear" tabla de producciones realizadas
    public void cargarProduccionesRealizadas(ArrayList<Producidos> listaProdu, ArrayList <Producto> pro) {
        for (int i = 0; i < listaProdu.size(); i++) {
            
            int codProducto = listaProdu.get(i).getProducto();
            String nomPro = "";
            for (int j = 0; j < pro.size(); j++) {
                if(pro.get(j).getCodigoPro()== codProducto){
                    nomPro = pro.get(j).getNombrePro();
                }
            }
            
            
            mTabla.addRow(new Object[]{
                listaProdu.get(i).getIdProducidos(),
                nomPro,
                listaProdu.get(i).getCantidadProducida(),});
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblprodurea = new javax.swing.JTable();

        setClosable(true);
        setTitle("Producidos realizadas");

        tblprodurea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Producido", "Producto", "Cantidad "
            }
        ));
        jScrollPane1.setViewportView(tblprodurea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblprodurea;
    // End of variables declaration//GEN-END:variables
}
