/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.MateriaPrima;
import modelo.Produccion;
import modelo.Producto;

/**
 *
 * @author Amelia Wolf
 */
public class VentanaProduccion extends javax.swing.JInternalFrame {

    private DefaultTableModel mProdu;
    private DefaultTableModel mReceta;
    private DefaultComboBoxModel mPro1;
    private DefaultComboBoxModel mPro2;
    private DefaultComboBoxModel mMatPri;

    /**
     * Creates new form VentanaProduccion
     */
    public VentanaProduccion() {
        initComponents();
        mProdu = (DefaultTableModel) tblproduccion.getModel();
        mReceta = (DefaultTableModel) tblreceta.getModel();
        mPro1 = (DefaultComboBoxModel) cmbproducto1.getModel();
        cmbproducto1.setActionCommand("cmbproducto1");
        mPro2 = (DefaultComboBoxModel) cmbproducto2.getModel();
        cmbproducto2.setActionCommand("cmbproducto2");
        mMatPri = (DefaultComboBoxModel) cmbmatpri.getModel();
        cmbmatpri.setActionCommand("cmbmatpri");
        System.out.println(btnproducir.getActionCommand());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    //Haciendo Listeners de los txt y btn
    public int getProducto1() {
        return cmbproducto1.getSelectedIndex();
    }

    public int getProducto2() {
        return cmbproducto2.getSelectedIndex();
    }

    public int getMatPri() {
        return cmbmatpri.getSelectedIndex();
    }

    public int getCantidad() {
        return Integer.parseInt(txtcantidad.getText().trim());
    }

    public int getCuantos() {
        return Integer.parseInt(txtcuantos.getText().trim());
    }
    
    public int getTablaReceta(){
        int sel = tblreceta.getSelectedRow();
        int recetita = (Integer) tblreceta.getValueAt(sel, 0);   
        return recetita;
    }
    
    public int getCodMatPriReceta(){
        int sel = tblreceta.getSelectedRow();
        int recetita = (Integer) tblreceta.getValueAt(sel, 1);   
        return recetita;
    }
    

    public void addListenerSelectProdu1(ActionListener listen) {
        cmbproducto1.addActionListener(listen);
    }

    public void addListenerSelectProdu2(ActionListener listen) {
        cmbproducto2.addActionListener(listen);
    }

    public void addListenerProducir(ActionListener listen) {
        btnproducir.addActionListener(listen);
    }

    public void addListenerAgregar(ActionListener listen) {
        btnagregar.addActionListener(listen);
    }

    public void addListenerEliminar(ActionListener listen) {
        btneliminar.addActionListener(listen);
    }

    public void addListenerActualizar(ActionListener listen) {
        btnactualizar.addActionListener(listen);
    }

    public boolean revisartabla() {
        if (tblreceta.getRowCount() == 0) {
            return false;
        }
        return true;
    }

    //Vaciar la tablas 
    public void limpiarTablaProduccion() {
        for (int i = mProdu.getRowCount() - 1; i >= 0; i--) {
            mProdu.removeRow(i);
        }
    }

    public void limpiarTablaReceta() {
        for (int i = mReceta.getRowCount() - 1; i >= 0; i--) {
            mReceta.removeRow(i);

        }
    }

    //"Crear" tabla de produccion
    public void cargarProduccion(ArrayList<Produccion> listaProdu, ArrayList<MateriaPrima> matpri) {
        limpiarTablaProduccion();
        for (int i = 0; i < listaProdu.size(); i++) {
            
            int codMatPri = listaProdu.get(i).getMateriaPrima();
            String nomMatPri = "";
            for (int j = 0; j < matpri.size(); j++) {
                if(matpri.get(j).getCodigoMatPri() == codMatPri){
                    nomMatPri = matpri.get(j).getNombreMatPri();
                }
            }
            
            mProdu.addRow(new Object[]{
                nomMatPri,
                //listaProdu.get(i).getMateriaPrima(),
                listaProdu.get(i).getCantidadMatPrima(),
                "",});
        }
    }

    //"Crear" tabla de  Receta
    public void cargarReceta(ArrayList<Produccion> receta, ArrayList<MateriaPrima> matpri) {
        limpiarTablaReceta();
        for (int i = 0; i < receta.size(); i++) {
            
            int codMatPri = receta.get(i).getMateriaPrima();
            String nomMatPri = "";
            for (int j = 0; j < matpri.size(); j++) {
                if(matpri.get(j).getCodigoMatPri() == codMatPri){
                    nomMatPri = matpri.get(j).getNombreMatPri();
                }
            }
            mReceta.addRow(new Object[]{
                receta.get(i).getCodigoProdu(),
                receta.get(i).getMateriaPrima(),
                nomMatPri,
                receta.get(i).getCantidadMatPrima()});
        }
    }

    //Cargar los datos de les ComboBox
    public void cargarProducto(ArrayList<Producto> listaPro) {
        mPro1.removeAllElements();
        mPro2.removeAllElements();
        for (int i = 0; i < listaPro.size(); i++) {
            mPro1.addElement(listaPro.get(i).getNombrePro());
            mPro2.addElement(listaPro.get(i).getNombrePro());
        }
    }

    public void cargarMatPri(ArrayList<MateriaPrima> listaMatPrimas) {
        mMatPri.removeAllElements();
        for (int i = 0; i < listaMatPrimas.size(); i++) {
            mMatPri.addElement(listaMatPrimas.get(i).getNombreMatPri());
        }
    }

    public boolean revisaProduccion() {
        if (txtcantidad.getText().replaceAll(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos incompletos, por favor llene todos lo campos");
            return false;
        }
        return true;
    }

    public boolean revisaReceta() {
        if (txtcuantos.getText().replaceAll(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos incompletos, por favor llene todos lo campos");
            return false;
        }
        return true;
    }

    public void cancelarAction() {
        btneliminar.setEnabled(false);
        btnactualizar.setEnabled(false);
        btnagregar.setText("Agregar");
        btnagregar.setActionCommand("agregar");
        tblreceta.clearSelection();
        cmbproducto2.setEnabled(true);
        limpiarDatos();
    }

    public void limpiarDatos() {
        txtcantidad.setText("");
        txtcuantos.setText("");
    }

    public void gestionMensajes(String mensaje, String titulo, int icono) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, icono);
    }
    
    public void calcular (){
        int cant = 0;
        if (!txtcantidad.getText().replaceAll(" ", "").isEmpty()) {
            cant = Integer.parseUnsignedInt(txtcantidad.getText().trim());
        }
        for (int i = 0; i < mProdu.getRowCount(); i++) {
            int total = cant * Integer.parseInt(tblproduccion.getValueAt(i, 1).toString());
            mProdu.setValueAt(total, i, 2);
        }
    }
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlproduccion = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lblcuantos1 = new javax.swing.JLabel();
        pnlproducir = new javax.swing.JPanel();
        lblcantidad = new javax.swing.JLabel();
        btnproducir = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduccion = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbproducto1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblproducto = new javax.swing.JLabel();
        cmbproducto2 = new javax.swing.JComboBox<>();
        lblcuantos2 = new javax.swing.JLabel();
        txtcuantos = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        lblmatpri = new javax.swing.JLabel();
        cmbmatpri = new javax.swing.JComboBox<>();
        btnactualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblreceta = new javax.swing.JTable();

        setClosable(true);
        setTitle("Producción");

        pnlproduccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo producto"));

        lblnombre.setText("Nombre:");

        lblcuantos1.setText("Cuantos:");

        pnlproducir.setBorder(javax.swing.BorderFactory.createTitledBorder("Producir"));

        lblcantidad.setText("Cantidad:");

        btnproducir.setText("Producir");

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });

        tblproduccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia Prima", "Cantidad c/u", "Cantidad total"
            }
        ));
        jScrollPane1.setViewportView(tblproduccion);

        javax.swing.GroupLayout pnlproducirLayout = new javax.swing.GroupLayout(pnlproducir);
        pnlproducir.setLayout(pnlproducirLayout);
        pnlproducirLayout.setHorizontalGroup(
            pnlproducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlproducirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlproducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlproducirLayout.createSequentialGroup()
                        .addComponent(lblcantidad)
                        .addGroup(pnlproducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlproducirLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btnproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlproducirLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlproducirLayout.setVerticalGroup(
            pnlproducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlproducirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlproducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcantidad)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnproducir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout pnlproduccionLayout = new javax.swing.GroupLayout(pnlproduccion);
        pnlproduccion.setLayout(pnlproduccionLayout);
        pnlproduccionLayout.setHorizontalGroup(
            pnlproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlproduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlproducir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlproduccionLayout.createSequentialGroup()
                        .addGroup(pnlproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlproduccionLayout.createSequentialGroup()
                                .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbproducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblcuantos1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 267, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlproduccionLayout.setVerticalGroup(
            pnlproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlproduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(cmbproducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(pnlproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336)
                .addComponent(lblcuantos1)
                .addGap(173, 173, 173)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar Receta"));

        lblproducto.setText("Producto: ");

        lblcuantos2.setText("Cuantos:");

        btneliminar.setText("Eliminar");
        btneliminar.setEnabled(false);

        btnagregar.setText("Agregar");

        lblmatpri.setText("Materia Prima requerida:");

        btnactualizar.setText("Actualizar");
        btnactualizar.setEnabled(false);

        tblreceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cod Mat Pri", "Materia Prima", "Gasta"
            }
        ));
        tblreceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrecetaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblreceta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblmatpri)
                                        .addComponent(lblproducto))
                                    .addComponent(lblcuantos2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbmatpri, 0, 213, Short.MAX_VALUE)
                                    .addComponent(cmbproducto2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtcuantos)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnagregar)
                                .addGap(44, 44, 44)
                                .addComponent(btneliminar)
                                .addGap(34, 34, 34)
                                .addComponent(btnactualizar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblproducto)
                    .addComponent(cmbproducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmatpri)
                    .addComponent(cmbmatpri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcuantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcuantos2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnactualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btneliminar))
                    .addComponent(btnagregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        calcular();
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void tblrecetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrecetaMouseClicked
        int sel = tblreceta.getSelectedRow();
        if (sel == -1) {
            if (tblreceta.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No hay registros");
            }
        } else {
            cmbproducto2.setEnabled(false);
            cmbmatpri.setSelectedItem(tblreceta.getValueAt(sel, 2).toString());
            txtcuantos.setText(tblreceta.getValueAt(sel, 3).toString());
            btneliminar.setEnabled(true);
            btnagregar.setText("Cancelar");
            btnagregar.setActionCommand("cancelar");
            btnactualizar.setEnabled(true);
        }
    }//GEN-LAST:event_tblrecetaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnproducir;
    private javax.swing.JComboBox<String> cmbmatpri;
    private javax.swing.JComboBox<String> cmbproducto1;
    private javax.swing.JComboBox<String> cmbproducto2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lblcuantos1;
    private javax.swing.JLabel lblcuantos2;
    private javax.swing.JLabel lblmatpri;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblproducto;
    private javax.swing.JPanel pnlproduccion;
    private javax.swing.JPanel pnlproducir;
    private javax.swing.JTable tblproduccion;
    private javax.swing.JTable tblreceta;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcuantos;
    // End of variables declaration//GEN-END:variables
}
