/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Vendedor;
import modelo.Venta;

/**
 *
 * @author Amelia Wolf
 */
public class VentanaVentRea extends javax.swing.JInternalFrame {

     private DefaultTableModel mTabla;
    /**
     * Creates new form VentanaVentRea
     */
    public VentanaVentRea() {
        initComponents();
        mTabla = (DefaultTableModel) tblventrea.getModel();
        
        //System.out.println(btnver.getActionCommand());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Haciendo Listeners de los txt y btn
    
    
    public int getcodigoVenta(){
        int sel = tblventrea.getSelectedRow();
        int venta = (Integer) tblventrea.getValueAt(sel, 0);   
        return venta;
    }
    
    public void addListenerVer(ActionListener listen) {
        btnver.addActionListener(listen);
    }
    
    //"Crear" tabla de ventasRealizadas
    public void cargarVentasRealizadas(ArrayList<Venta> listaVent, ArrayList <Vendedor> ven, ArrayList <Cliente> cli) {
        for (int i = 0; i < listaVent.size(); i++) {
            
            int codVendedor = listaVent.get(i).getVendedor();
            String nomVen = "";
            for (int j = 0; j < ven.size(); j++) {
                if(ven.get(j).getCodigoVen() == codVendedor){
                    nomVen = ven.get(j).getNombreVen();
                }
            }
            
            int codCliente = listaVent.get(i).getCliente();
            String nomCli = "";
            for (int j = 0; j < cli.size(); j++) {
                if(cli.get(j).getCodigoCli() == codCliente){
                    nomCli = cli.get(j).getNombreCli();
                }
            }
            
            mTabla.addRow(new Object[]{
                listaVent.get(i).getCodigoVenta(),
                nomVen,
                nomCli,
                listaVent.get(i).getTotal(),
                listaVent.get(i).getTipoVenta(),});
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblventrea = new javax.swing.JTable();
        btnver = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ventas Realizadas");

        tblventrea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Venta", "Vendedor", "Cliente", "Total", "Tipo Venta"
            }
        ));
        tblventrea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblventreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblventrea);

        btnver.setText("Ver Detalle");
        btnver.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(btnver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnver)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblventreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblventreaMouseClicked
        int sel = tblventrea.getSelectedRow();
        if(sel == -1){
            if(tblventrea.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"No hay registros");
            }
        }else {
            btnver.setEnabled(true);
        }
    }//GEN-LAST:event_tblventreaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblventrea;
    // End of variables declaration//GEN-END:variables
}
