/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Distribuidor;
import modelo.Ingreso;
import modelo.MateriaPrima;

/**
 *
 * @author Amelia Wolf
 */
public class VentanaIngRea extends javax.swing.JInternalFrame {
    private DefaultTableModel mTabla;
    /**
     * Creates new form VentanaIngRea
     */
    public VentanaIngRea() {
        initComponents();
        mTabla = (DefaultTableModel) tblingrea.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public int getcodigoIngreso(){
        int sel = tblingrea.getSelectedRow();
        int ingreso = (Integer) tblingrea.getValueAt(sel, 0);   
        return ingreso;
    }
    
    public void addListenerVer(ActionListener listen) {
        btnver.addActionListener(listen);
    }
    
    //"Crear" tabla de ingresosRealizadas
    public void cargarIngresosRealizados(ArrayList<Ingreso> listaIng, ArrayList<Distribuidor> distri) {
        for (int i = 0; i < listaIng.size(); i++) {
            
            int codDistribuidor = distri.get(i).getCodigoDis();
            String nomDistri = "";
            for (int j = 0; j < distri.size(); j++) {
                if(distri.get(j).getCodigoDis() == codDistribuidor){
                    nomDistri = distri.get(j).getNombreDis();
                }
            }
            
            
            mTabla.addRow(new Object[]{
                listaIng.get(i).getCodigoIng(),
                nomDistri,
                listaIng.get(i).getTotal(),});
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblingrea = new javax.swing.JTable();
        btnver = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ingresos realizados");

        tblingrea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Distribuidor", "Total"
            }
        ));
        tblingrea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblingreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblingrea);

        btnver.setText("Ver Detalle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnver)
                .addGap(247, 247, 247))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnver)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblingreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblingreaMouseClicked
        int sel = tblingrea.getSelectedRow();
        if(sel == -1){
            if(tblingrea.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"No hay registros");
            }
        }else {
            btnver.setEnabled(true);
        }
    }//GEN-LAST:event_tblingreaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblingrea;
    // End of variables declaration//GEN-END:variables
}
