/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.VentaDetalle;

/**
 *
 * @author Amelia Wolf
 */
public class VistaDetalleVenta extends javax.swing.JInternalFrame {

    private DefaultTableModel mTabla;

    /**
     * Creates new form VistaDetalleVenta
     */
    public VistaDetalleVenta() {
        initComponents();
        mTabla = (DefaultTableModel) tbldetventa.getModel();
    }

    public void cargarTabla(ArrayList<VentaDetalle> detventa, ArrayList<Producto> pro) {
        for (int i = 0; i < detventa.size(); i++) {

            int codProducto = detventa.get(i).getProducto();
            String nomPro = "";
            for (int x = 0; x < pro.size(); x++) {
                if (pro.get(x).getCodigoPro() == codProducto) {
                    nomPro = pro.get(x).getNombrePro();
                }
            }

            mTabla.addRow(new Object[]{
                detventa.get(i).getProducto(),
                nomPro,
                detventa.get(i).getPrecio(),
                detventa.get(i).getCantidad(),
                detventa.get(i).getTotal(),});
        }
    }
    
    //Vaciar la tabla 
    public void limpiarTabla() {
        for (int i = mTabla.getRowCount() - 1; i >= 0; i--) {
            mTabla.removeRow(i);
        }
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbldetventa = new javax.swing.JTable();
        btnsalir = new javax.swing.JButton();

        setTitle("Detalle Venta");

        tbldetventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Producto", "Producto", "Precio", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbldetventa);

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        limpiarTabla();
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldetventa;
    // End of variables declaration//GEN-END:variables
}
